name: ADongServer
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '15,45 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     
     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start HTTP via Ngrok
       if: ${{ failure() }}
       run: bash ssh.sh
       env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
 
        # This password you will use when authorizing via SSH 
        USER_PASS: ${{ secrets.USER_PASS }}
        
     - run: 'echo "$FRPC_INI" > frpc.ini'
       if: ${{ failure() }}
       shell: bash
       env:
         FRPC_INI: ${{secrets.FRPC_INI}}

     - run: 'echo "$ENV_PROPERTIES" > env.properties'
       if: ${{ failure() }}
       shell: bash
       env:
         ENV_PROPERTIES: ${{secrets.ENV_PROPERTIES}}
        
     - run: 'echo "$NGINX" > websocket.conf'
       if: ${{ failure() }}
       shell: bash
       env:
         NGINX: ${{secrets.NGINX}}
         
     - run: 'sudo cp websocket.conf /etc/nginx/conf.d/websocket.conf'
       if: ${{ failure() }}
       shell: bash
         
     - name: Start FRP
       if: ${{ failure() }}
       run: |
         wget https://github.com/fatedier/frp/releases/download/v0.33.0/frp_0.33.0_linux_amd64.tar.gz
         tar -xzvf frp_0.33.0_linux_amd64.tar.gz
         nohup ./frp_0.33.0_linux_amd64/frpc -c ./frpc.ini >/dev/null 2>&1 &

     - name: Start Docker
       if: ${{ failure() }}
       run: |
         sudo service nginx restart
         docker pull selenoid/chrome:89.0
         docker run -d -p 5701:8080 -p 4444:4444 --name=webapp --privileged=true -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)"/env.properties:/env.properties:ro rubyangxg/jd-qinglong:1.6
         docker ps
         # docker logs -f webapp
         
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 70m # Prevent to killing instance after failure
